### ISSUE TITLE
Payments of 200k SATs or more,  directly from lncli do not work. 

### ISSUE THREAD

**Issue by motolese** [BitcoinBeachBR/LNBits-Payment-Forward#10]
When the amount available at LNBits Hot Wallet is not enough, the payment is made by LNCLI command directly from the node. 

![image](https://user-images.githubusercontent.com/81449156/146614619-9b75d395-5c36-4715-8444-f6fec4d7a3ae.png)

**Comment by motolese** [comment]
All users are aware of the limitation of 200k SATs, but the user decided to help us run the test. 

So, today, a payment of 222k SATs wasn't completed.  

The donations were made, but the payment wasn't forwarded to the user's wallet. 

We sent the funds to the user manually, and we are waiting for the dev to solve the issue to run a new test.

**Comment by as-schug** [comment]
Podemos ter o problema de encontrar rotas para o valor desejado, como explicado no início.
Qual o destino do pagamento? O próprio node? O que acontece quando se tenta pagar a invoice gerada com o comando lncli diretamente?

**Comment by as-schug** [comment]
Corrected
