### ISSUE TITLE
Split fee - Donation Module

### ISSUE THREAD

**Issue by motolese** [BitcoinBeachBR/LNBits-Payment-Forward#7]
When a payment is received, make a donation of 50% of the fee, for a Local social project. 

Now we have 2 social projects only but can be more, so the script needs to guarantee, it will follow the queue 

I suggest a new file _donations.conf_ to include multiple lndurl invoices ordered like dis

1=SurfScholl=lndinvoiceurl
2=AnimalsCare=lndinvoiceurl
3=Other=lndinvoiceurl

And then keep tracking the last project who received a donation, and donate to the next.

**Comment by as-schug** [comment]
Added suport for multiple donation.
It can be configure via postgres database

![image](https://user-images.githubusercontent.com/67750682/144109631-c26df794-ecce-47cd-ab65-8c6e0940927a.png)

It splits fee and pay each invoice while forward payments

![image](https://user-images.githubusercontent.com/67750682/144109930-58d21a34-0518-41a9-96d2-5b65d51f0b2f.png)
